sudo: required

language: ruby

service: docker

before_install:
    - docker-compose up -d
    - docker-compose exec api_server rails db:migrate RAILS_ENV=test

script:
    - docker-compose exec api_server rails test
